/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as WRouteImport } from './routes/w'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces/new'
import { Route as WSlugRouteImport } from './routes/w/$slug'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthRecoverRouteImport } from './routes/auth/recover'
import { Route as WSlugTicketsRouteImport } from './routes/w/$slug/tickets'
import { Route as WSlugTeamsRouteImport } from './routes/w/$slug/teams'
import { Route as WSlugSettingsRouteImport } from './routes/w/$slug/settings'
import { Route as WSlugOverviewRouteImport } from './routes/w/$slug/overview'
import { Route as WSlugAnalyticsRouteImport } from './routes/w/$slug/analytics'
import { Route as WSlugAgentsRouteImport } from './routes/w/$slug/agents'
import { Route as WSlugTicketsIndexRouteImport } from './routes/w/$slug/tickets/index'
import { Route as WSlugTicketsIdRouteImport } from './routes/w/$slug/tickets/$id'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const WRoute = WRouteImport.update({
  id: '/w',
  path: '/w',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AuthRoute,
} as any)
const WSlugTicketsRoute = WSlugTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugTeamsRoute = WSlugTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugSettingsRoute = WSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugOverviewRoute = WSlugOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugAnalyticsRoute = WSlugAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugAgentsRoute = WSlugAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugTicketsIndexRoute = WSlugTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugTicketsRoute,
} as any)
const WSlugTicketsIdRoute = WSlugTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WSlugTicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/w': typeof WRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/w/$slug/agents': typeof WSlugAgentsRoute
  '/w/$slug/analytics': typeof WSlugAnalyticsRoute
  '/w/$slug/overview': typeof WSlugOverviewRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/teams': typeof WSlugTeamsRoute
  '/w/$slug/tickets': typeof WSlugTicketsRouteWithChildren
  '/w/$slug/tickets/$id': typeof WSlugTicketsIdRoute
  '/w/$slug/tickets/': typeof WSlugTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/w': typeof WRouteWithChildren
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/w/$slug/agents': typeof WSlugAgentsRoute
  '/w/$slug/analytics': typeof WSlugAnalyticsRoute
  '/w/$slug/overview': typeof WSlugOverviewRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/teams': typeof WSlugTeamsRoute
  '/w/$slug/tickets/$id': typeof WSlugTicketsIdRoute
  '/w/$slug/tickets': typeof WSlugTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/w': typeof WRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/w/$slug/agents': typeof WSlugAgentsRoute
  '/w/$slug/analytics': typeof WSlugAnalyticsRoute
  '/w/$slug/overview': typeof WSlugOverviewRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/teams': typeof WSlugTeamsRoute
  '/w/$slug/tickets': typeof WSlugTicketsRouteWithChildren
  '/w/$slug/tickets/$id': typeof WSlugTicketsIdRoute
  '/w/$slug/tickets/': typeof WSlugTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/w'
    | '/workspaces'
    | '/auth/recover'
    | '/auth/signin'
    | '/auth/signup'
    | '/w/$slug'
    | '/workspaces/new'
    | '/workspaces/'
    | '/w/$slug/agents'
    | '/w/$slug/analytics'
    | '/w/$slug/overview'
    | '/w/$slug/settings'
    | '/w/$slug/teams'
    | '/w/$slug/tickets'
    | '/w/$slug/tickets/$id'
    | '/w/$slug/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/w'
    | '/auth/recover'
    | '/auth/signin'
    | '/auth/signup'
    | '/w/$slug'
    | '/workspaces/new'
    | '/workspaces'
    | '/w/$slug/agents'
    | '/w/$slug/analytics'
    | '/w/$slug/overview'
    | '/w/$slug/settings'
    | '/w/$slug/teams'
    | '/w/$slug/tickets/$id'
    | '/w/$slug/tickets'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/w'
    | '/workspaces'
    | '/auth/recover'
    | '/auth/signin'
    | '/auth/signup'
    | '/w/$slug'
    | '/workspaces/new'
    | '/workspaces/'
    | '/w/$slug/agents'
    | '/w/$slug/analytics'
    | '/w/$slug/overview'
    | '/w/$slug/settings'
    | '/w/$slug/teams'
    | '/w/$slug/tickets'
    | '/w/$slug/tickets/$id'
    | '/w/$slug/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  WRoute: typeof WRouteWithChildren
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w': {
      id: '/w'
      path: '/w'
      fullPath: '/w'
      preLoaderRoute: typeof WRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof WRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/recover': {
      id: '/auth/recover'
      path: '/recover'
      fullPath: '/auth/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof AuthRoute
    }
    '/w/$slug/tickets': {
      id: '/w/$slug/tickets'
      path: '/tickets'
      fullPath: '/w/$slug/tickets'
      preLoaderRoute: typeof WSlugTicketsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/teams': {
      id: '/w/$slug/teams'
      path: '/teams'
      fullPath: '/w/$slug/teams'
      preLoaderRoute: typeof WSlugTeamsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/settings': {
      id: '/w/$slug/settings'
      path: '/settings'
      fullPath: '/w/$slug/settings'
      preLoaderRoute: typeof WSlugSettingsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/overview': {
      id: '/w/$slug/overview'
      path: '/overview'
      fullPath: '/w/$slug/overview'
      preLoaderRoute: typeof WSlugOverviewRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/analytics': {
      id: '/w/$slug/analytics'
      path: '/analytics'
      fullPath: '/w/$slug/analytics'
      preLoaderRoute: typeof WSlugAnalyticsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/agents': {
      id: '/w/$slug/agents'
      path: '/agents'
      fullPath: '/w/$slug/agents'
      preLoaderRoute: typeof WSlugAgentsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/tickets/': {
      id: '/w/$slug/tickets/'
      path: '/'
      fullPath: '/w/$slug/tickets/'
      preLoaderRoute: typeof WSlugTicketsIndexRouteImport
      parentRoute: typeof WSlugTicketsRoute
    }
    '/w/$slug/tickets/$id': {
      id: '/w/$slug/tickets/$id'
      path: '/$id'
      fullPath: '/w/$slug/tickets/$id'
      preLoaderRoute: typeof WSlugTicketsIdRouteImport
      parentRoute: typeof WSlugTicketsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRecoverRoute: AuthRecoverRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface WSlugTicketsRouteChildren {
  WSlugTicketsIdRoute: typeof WSlugTicketsIdRoute
  WSlugTicketsIndexRoute: typeof WSlugTicketsIndexRoute
}

const WSlugTicketsRouteChildren: WSlugTicketsRouteChildren = {
  WSlugTicketsIdRoute: WSlugTicketsIdRoute,
  WSlugTicketsIndexRoute: WSlugTicketsIndexRoute,
}

const WSlugTicketsRouteWithChildren = WSlugTicketsRoute._addFileChildren(
  WSlugTicketsRouteChildren,
)

interface WSlugRouteChildren {
  WSlugAgentsRoute: typeof WSlugAgentsRoute
  WSlugAnalyticsRoute: typeof WSlugAnalyticsRoute
  WSlugOverviewRoute: typeof WSlugOverviewRoute
  WSlugSettingsRoute: typeof WSlugSettingsRoute
  WSlugTeamsRoute: typeof WSlugTeamsRoute
  WSlugTicketsRoute: typeof WSlugTicketsRouteWithChildren
}

const WSlugRouteChildren: WSlugRouteChildren = {
  WSlugAgentsRoute: WSlugAgentsRoute,
  WSlugAnalyticsRoute: WSlugAnalyticsRoute,
  WSlugOverviewRoute: WSlugOverviewRoute,
  WSlugSettingsRoute: WSlugSettingsRoute,
  WSlugTeamsRoute: WSlugTeamsRoute,
  WSlugTicketsRoute: WSlugTicketsRouteWithChildren,
}

const WSlugRouteWithChildren = WSlugRoute._addFileChildren(WSlugRouteChildren)

interface WRouteChildren {
  WSlugRoute: typeof WSlugRouteWithChildren
}

const WRouteChildren: WRouteChildren = {
  WSlugRoute: WSlugRouteWithChildren,
}

const WRouteWithChildren = WRoute._addFileChildren(WRouteChildren)

interface WorkspacesRouteChildren {
  WorkspacesNewRoute: typeof WorkspacesNewRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesNewRoute: WorkspacesNewRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  WRoute: WRouteWithChildren,
  WorkspacesRoute: WorkspacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
