/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as WRouteImport } from './routes/w'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as Char123LangChar125RouteRouteImport } from './routes/{-$lang}/route'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as Char123LangChar125TermsRouteImport } from './routes/{-$lang}/terms'
import { Route as Char123LangChar125StatusRouteImport } from './routes/{-$lang}/status'
import { Route as Char123LangChar125SolutionsRouteImport } from './routes/{-$lang}/solutions'
import { Route as Char123LangChar125SecurityRouteImport } from './routes/{-$lang}/security'
import { Route as Char123LangChar125PrivacyRouteImport } from './routes/{-$lang}/privacy'
import { Route as Char123LangChar125PricingRouteImport } from './routes/{-$lang}/pricing'
import { Route as Char123LangChar125IntegrationsRouteImport } from './routes/{-$lang}/integrations'
import { Route as Char123LangChar125HelpRouteImport } from './routes/{-$lang}/help'
import { Route as Char123LangChar125FeaturesRouteImport } from './routes/{-$lang}/features'
import { Route as Char123LangChar125CustomersRouteImport } from './routes/{-$lang}/customers'
import { Route as Char123LangChar125ContactRouteImport } from './routes/{-$lang}/contact'
import { Route as Char123LangChar125ChangelogRouteImport } from './routes/{-$lang}/changelog'
import { Route as Char123LangChar125CareersRouteImport } from './routes/{-$lang}/careers'
import { Route as Char123LangChar125BlogRouteImport } from './routes/{-$lang}/blog'
import { Route as Char123LangChar125AboutRouteImport } from './routes/{-$lang}/about'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces/new'
import { Route as WSlugRouteImport } from './routes/w/$slug'
import { Route as AuthTwoFactorRouteImport } from './routes/auth/two-factor'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRecoverRouteImport } from './routes/auth/recover'
import { Route as Char123LangChar125SolutionsSupportTeamsRouteImport } from './routes/{-$lang}/solutions/support-teams'
import { Route as Char123LangChar125SolutionsSoloSmallTeamsRouteImport } from './routes/{-$lang}/solutions/solo-small-teams'
import { Route as Char123LangChar125SolutionsAgenciesRouteImport } from './routes/{-$lang}/solutions/agencies'
import { Route as WSlugTicketsRouteImport } from './routes/w/$slug/tickets'
import { Route as WSlugTeamsRouteImport } from './routes/w/$slug/teams'
import { Route as WSlugSettingsRouteImport } from './routes/w/$slug/settings'
import { Route as WSlugProfileRouteImport } from './routes/w/$slug/profile'
import { Route as WSlugOverviewRouteImport } from './routes/w/$slug/overview'
import { Route as WSlugNotificationsRouteImport } from './routes/w/$slug/notifications'
import { Route as WSlugMarketplaceRouteImport } from './routes/w/$slug/marketplace'
import { Route as WSlugAnalyticsRouteImport } from './routes/w/$slug/analytics'
import { Route as WSlugTicketsIndexRouteImport } from './routes/w/$slug/tickets/index'
import { Route as WSlugTicketsIdRouteImport } from './routes/w/$slug/tickets/$id'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const WRoute = WRouteImport.update({
  id: '/w',
  path: '/w',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125RouteRoute = Char123LangChar125RouteRouteImport.update({
  id: '/{-$lang}',
  path: '/{-$lang}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char123LangChar125RouteRoute,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRoute,
} as any)
const Char123LangChar125TermsRoute = Char123LangChar125TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => Char123LangChar125RouteRoute,
} as any)
const Char123LangChar125StatusRoute =
  Char123LangChar125StatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125SolutionsRoute =
  Char123LangChar125SolutionsRouteImport.update({
    id: '/solutions',
    path: '/solutions',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125SecurityRoute =
  Char123LangChar125SecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125PrivacyRoute =
  Char123LangChar125PrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125PricingRoute =
  Char123LangChar125PricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125IntegrationsRoute =
  Char123LangChar125IntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125HelpRoute = Char123LangChar125HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => Char123LangChar125RouteRoute,
} as any)
const Char123LangChar125FeaturesRoute =
  Char123LangChar125FeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125CustomersRoute =
  Char123LangChar125CustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125ContactRoute =
  Char123LangChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125ChangelogRoute =
  Char123LangChar125ChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125CareersRoute =
  Char123LangChar125CareersRouteImport.update({
    id: '/careers',
    path: '/careers',
    getParentRoute: () => Char123LangChar125RouteRoute,
  } as any)
const Char123LangChar125BlogRoute = Char123LangChar125BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => Char123LangChar125RouteRoute,
} as any)
const Char123LangChar125AboutRoute = Char123LangChar125AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => Char123LangChar125RouteRoute,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AuthRoute,
} as any)
const Char123LangChar125SolutionsSupportTeamsRoute =
  Char123LangChar125SolutionsSupportTeamsRouteImport.update({
    id: '/support-teams',
    path: '/support-teams',
    getParentRoute: () => Char123LangChar125SolutionsRoute,
  } as any)
const Char123LangChar125SolutionsSoloSmallTeamsRoute =
  Char123LangChar125SolutionsSoloSmallTeamsRouteImport.update({
    id: '/solo-small-teams',
    path: '/solo-small-teams',
    getParentRoute: () => Char123LangChar125SolutionsRoute,
  } as any)
const Char123LangChar125SolutionsAgenciesRoute =
  Char123LangChar125SolutionsAgenciesRouteImport.update({
    id: '/agencies',
    path: '/agencies',
    getParentRoute: () => Char123LangChar125SolutionsRoute,
  } as any)
const WSlugTicketsRoute = WSlugTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugTeamsRoute = WSlugTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugSettingsRoute = WSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugProfileRoute = WSlugProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugOverviewRoute = WSlugOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugNotificationsRoute = WSlugNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugMarketplaceRoute = WSlugMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugAnalyticsRoute = WSlugAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugTicketsIndexRoute = WSlugTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugTicketsRoute,
} as any)
const WSlugTicketsIdRoute = WSlugTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WSlugTicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/w': typeof WRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/blog': typeof Char123LangChar125BlogRoute
  '/{-$lang}/careers': typeof Char123LangChar125CareersRoute
  '/{-$lang}/changelog': typeof Char123LangChar125ChangelogRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/customers': typeof Char123LangChar125CustomersRoute
  '/{-$lang}/features': typeof Char123LangChar125FeaturesRoute
  '/{-$lang}/help': typeof Char123LangChar125HelpRoute
  '/{-$lang}/integrations': typeof Char123LangChar125IntegrationsRoute
  '/{-$lang}/pricing': typeof Char123LangChar125PricingRoute
  '/{-$lang}/privacy': typeof Char123LangChar125PrivacyRoute
  '/{-$lang}/security': typeof Char123LangChar125SecurityRoute
  '/{-$lang}/solutions': typeof Char123LangChar125SolutionsRouteWithChildren
  '/{-$lang}/status': typeof Char123LangChar125StatusRoute
  '/{-$lang}/terms': typeof Char123LangChar125TermsRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/w/$slug/analytics': typeof WSlugAnalyticsRoute
  '/w/$slug/marketplace': typeof WSlugMarketplaceRoute
  '/w/$slug/notifications': typeof WSlugNotificationsRoute
  '/w/$slug/overview': typeof WSlugOverviewRoute
  '/w/$slug/profile': typeof WSlugProfileRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/teams': typeof WSlugTeamsRoute
  '/w/$slug/tickets': typeof WSlugTicketsRouteWithChildren
  '/{-$lang}/solutions/agencies': typeof Char123LangChar125SolutionsAgenciesRoute
  '/{-$lang}/solutions/solo-small-teams': typeof Char123LangChar125SolutionsSoloSmallTeamsRoute
  '/{-$lang}/solutions/support-teams': typeof Char123LangChar125SolutionsSupportTeamsRoute
  '/w/$slug/tickets/$id': typeof WSlugTicketsIdRoute
  '/w/$slug/tickets/': typeof WSlugTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/w': typeof WRouteWithChildren
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/blog': typeof Char123LangChar125BlogRoute
  '/{-$lang}/careers': typeof Char123LangChar125CareersRoute
  '/{-$lang}/changelog': typeof Char123LangChar125ChangelogRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/customers': typeof Char123LangChar125CustomersRoute
  '/{-$lang}/features': typeof Char123LangChar125FeaturesRoute
  '/{-$lang}/help': typeof Char123LangChar125HelpRoute
  '/{-$lang}/integrations': typeof Char123LangChar125IntegrationsRoute
  '/{-$lang}/pricing': typeof Char123LangChar125PricingRoute
  '/{-$lang}/privacy': typeof Char123LangChar125PrivacyRoute
  '/{-$lang}/security': typeof Char123LangChar125SecurityRoute
  '/{-$lang}/solutions': typeof Char123LangChar125SolutionsRouteWithChildren
  '/{-$lang}/status': typeof Char123LangChar125StatusRoute
  '/{-$lang}/terms': typeof Char123LangChar125TermsRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/w/$slug/analytics': typeof WSlugAnalyticsRoute
  '/w/$slug/marketplace': typeof WSlugMarketplaceRoute
  '/w/$slug/notifications': typeof WSlugNotificationsRoute
  '/w/$slug/overview': typeof WSlugOverviewRoute
  '/w/$slug/profile': typeof WSlugProfileRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/teams': typeof WSlugTeamsRoute
  '/{-$lang}/solutions/agencies': typeof Char123LangChar125SolutionsAgenciesRoute
  '/{-$lang}/solutions/solo-small-teams': typeof Char123LangChar125SolutionsSoloSmallTeamsRoute
  '/{-$lang}/solutions/support-teams': typeof Char123LangChar125SolutionsSupportTeamsRoute
  '/w/$slug/tickets/$id': typeof WSlugTicketsIdRoute
  '/w/$slug/tickets': typeof WSlugTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$lang}': typeof Char123LangChar125RouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/w': typeof WRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/{-$lang}/about': typeof Char123LangChar125AboutRoute
  '/{-$lang}/blog': typeof Char123LangChar125BlogRoute
  '/{-$lang}/careers': typeof Char123LangChar125CareersRoute
  '/{-$lang}/changelog': typeof Char123LangChar125ChangelogRoute
  '/{-$lang}/contact': typeof Char123LangChar125ContactRoute
  '/{-$lang}/customers': typeof Char123LangChar125CustomersRoute
  '/{-$lang}/features': typeof Char123LangChar125FeaturesRoute
  '/{-$lang}/help': typeof Char123LangChar125HelpRoute
  '/{-$lang}/integrations': typeof Char123LangChar125IntegrationsRoute
  '/{-$lang}/pricing': typeof Char123LangChar125PricingRoute
  '/{-$lang}/privacy': typeof Char123LangChar125PrivacyRoute
  '/{-$lang}/security': typeof Char123LangChar125SecurityRoute
  '/{-$lang}/solutions': typeof Char123LangChar125SolutionsRouteWithChildren
  '/{-$lang}/status': typeof Char123LangChar125StatusRoute
  '/{-$lang}/terms': typeof Char123LangChar125TermsRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/w/$slug/analytics': typeof WSlugAnalyticsRoute
  '/w/$slug/marketplace': typeof WSlugMarketplaceRoute
  '/w/$slug/notifications': typeof WSlugNotificationsRoute
  '/w/$slug/overview': typeof WSlugOverviewRoute
  '/w/$slug/profile': typeof WSlugProfileRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/teams': typeof WSlugTeamsRoute
  '/w/$slug/tickets': typeof WSlugTicketsRouteWithChildren
  '/{-$lang}/solutions/agencies': typeof Char123LangChar125SolutionsAgenciesRoute
  '/{-$lang}/solutions/solo-small-teams': typeof Char123LangChar125SolutionsSoloSmallTeamsRoute
  '/{-$lang}/solutions/support-teams': typeof Char123LangChar125SolutionsSupportTeamsRoute
  '/w/$slug/tickets/$id': typeof WSlugTicketsIdRoute
  '/w/$slug/tickets/': typeof WSlugTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$lang}'
    | '/auth'
    | '/w'
    | '/workspaces'
    | '/auth/recover'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/two-factor'
    | '/w/$slug'
    | '/workspaces/new'
    | '/{-$lang}/about'
    | '/{-$lang}/blog'
    | '/{-$lang}/careers'
    | '/{-$lang}/changelog'
    | '/{-$lang}/contact'
    | '/{-$lang}/customers'
    | '/{-$lang}/features'
    | '/{-$lang}/help'
    | '/{-$lang}/integrations'
    | '/{-$lang}/pricing'
    | '/{-$lang}/privacy'
    | '/{-$lang}/security'
    | '/{-$lang}/solutions'
    | '/{-$lang}/status'
    | '/{-$lang}/terms'
    | '/workspaces/'
    | '/{-$lang}/'
    | '/w/$slug/analytics'
    | '/w/$slug/marketplace'
    | '/w/$slug/notifications'
    | '/w/$slug/overview'
    | '/w/$slug/profile'
    | '/w/$slug/settings'
    | '/w/$slug/teams'
    | '/w/$slug/tickets'
    | '/{-$lang}/solutions/agencies'
    | '/{-$lang}/solutions/solo-small-teams'
    | '/{-$lang}/solutions/support-teams'
    | '/w/$slug/tickets/$id'
    | '/w/$slug/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/w'
    | '/auth/recover'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/two-factor'
    | '/w/$slug'
    | '/workspaces/new'
    | '/{-$lang}/about'
    | '/{-$lang}/blog'
    | '/{-$lang}/careers'
    | '/{-$lang}/changelog'
    | '/{-$lang}/contact'
    | '/{-$lang}/customers'
    | '/{-$lang}/features'
    | '/{-$lang}/help'
    | '/{-$lang}/integrations'
    | '/{-$lang}/pricing'
    | '/{-$lang}/privacy'
    | '/{-$lang}/security'
    | '/{-$lang}/solutions'
    | '/{-$lang}/status'
    | '/{-$lang}/terms'
    | '/workspaces'
    | '/{-$lang}'
    | '/w/$slug/analytics'
    | '/w/$slug/marketplace'
    | '/w/$slug/notifications'
    | '/w/$slug/overview'
    | '/w/$slug/profile'
    | '/w/$slug/settings'
    | '/w/$slug/teams'
    | '/{-$lang}/solutions/agencies'
    | '/{-$lang}/solutions/solo-small-teams'
    | '/{-$lang}/solutions/support-teams'
    | '/w/$slug/tickets/$id'
    | '/w/$slug/tickets'
  id:
    | '__root__'
    | '/{-$lang}'
    | '/auth'
    | '/w'
    | '/workspaces'
    | '/auth/recover'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/two-factor'
    | '/w/$slug'
    | '/workspaces/new'
    | '/{-$lang}/about'
    | '/{-$lang}/blog'
    | '/{-$lang}/careers'
    | '/{-$lang}/changelog'
    | '/{-$lang}/contact'
    | '/{-$lang}/customers'
    | '/{-$lang}/features'
    | '/{-$lang}/help'
    | '/{-$lang}/integrations'
    | '/{-$lang}/pricing'
    | '/{-$lang}/privacy'
    | '/{-$lang}/security'
    | '/{-$lang}/solutions'
    | '/{-$lang}/status'
    | '/{-$lang}/terms'
    | '/workspaces/'
    | '/{-$lang}/'
    | '/w/$slug/analytics'
    | '/w/$slug/marketplace'
    | '/w/$slug/notifications'
    | '/w/$slug/overview'
    | '/w/$slug/profile'
    | '/w/$slug/settings'
    | '/w/$slug/teams'
    | '/w/$slug/tickets'
    | '/{-$lang}/solutions/agencies'
    | '/{-$lang}/solutions/solo-small-teams'
    | '/{-$lang}/solutions/support-teams'
    | '/w/$slug/tickets/$id'
    | '/w/$slug/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LangChar125RouteRoute: typeof Char123LangChar125RouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  WRoute: typeof WRouteWithChildren
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w': {
      id: '/w'
      path: '/w'
      fullPath: '/w'
      preLoaderRoute: typeof WRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}': {
      id: '/{-$lang}'
      path: '/{-$lang}'
      fullPath: '/{-$lang}'
      preLoaderRoute: typeof Char123LangChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/{-$lang}/terms': {
      id: '/{-$lang}/terms'
      path: '/terms'
      fullPath: '/{-$lang}/terms'
      preLoaderRoute: typeof Char123LangChar125TermsRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/status': {
      id: '/{-$lang}/status'
      path: '/status'
      fullPath: '/{-$lang}/status'
      preLoaderRoute: typeof Char123LangChar125StatusRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/solutions': {
      id: '/{-$lang}/solutions'
      path: '/solutions'
      fullPath: '/{-$lang}/solutions'
      preLoaderRoute: typeof Char123LangChar125SolutionsRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/security': {
      id: '/{-$lang}/security'
      path: '/security'
      fullPath: '/{-$lang}/security'
      preLoaderRoute: typeof Char123LangChar125SecurityRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/privacy': {
      id: '/{-$lang}/privacy'
      path: '/privacy'
      fullPath: '/{-$lang}/privacy'
      preLoaderRoute: typeof Char123LangChar125PrivacyRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/pricing': {
      id: '/{-$lang}/pricing'
      path: '/pricing'
      fullPath: '/{-$lang}/pricing'
      preLoaderRoute: typeof Char123LangChar125PricingRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/integrations': {
      id: '/{-$lang}/integrations'
      path: '/integrations'
      fullPath: '/{-$lang}/integrations'
      preLoaderRoute: typeof Char123LangChar125IntegrationsRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/help': {
      id: '/{-$lang}/help'
      path: '/help'
      fullPath: '/{-$lang}/help'
      preLoaderRoute: typeof Char123LangChar125HelpRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/features': {
      id: '/{-$lang}/features'
      path: '/features'
      fullPath: '/{-$lang}/features'
      preLoaderRoute: typeof Char123LangChar125FeaturesRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/customers': {
      id: '/{-$lang}/customers'
      path: '/customers'
      fullPath: '/{-$lang}/customers'
      preLoaderRoute: typeof Char123LangChar125CustomersRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/contact': {
      id: '/{-$lang}/contact'
      path: '/contact'
      fullPath: '/{-$lang}/contact'
      preLoaderRoute: typeof Char123LangChar125ContactRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/changelog': {
      id: '/{-$lang}/changelog'
      path: '/changelog'
      fullPath: '/{-$lang}/changelog'
      preLoaderRoute: typeof Char123LangChar125ChangelogRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/careers': {
      id: '/{-$lang}/careers'
      path: '/careers'
      fullPath: '/{-$lang}/careers'
      preLoaderRoute: typeof Char123LangChar125CareersRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/blog': {
      id: '/{-$lang}/blog'
      path: '/blog'
      fullPath: '/{-$lang}/blog'
      preLoaderRoute: typeof Char123LangChar125BlogRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/{-$lang}/about': {
      id: '/{-$lang}/about'
      path: '/about'
      fullPath: '/{-$lang}/about'
      preLoaderRoute: typeof Char123LangChar125AboutRouteImport
      parentRoute: typeof Char123LangChar125RouteRoute
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof WRoute
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/recover': {
      id: '/auth/recover'
      path: '/recover'
      fullPath: '/auth/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof AuthRoute
    }
    '/{-$lang}/solutions/support-teams': {
      id: '/{-$lang}/solutions/support-teams'
      path: '/support-teams'
      fullPath: '/{-$lang}/solutions/support-teams'
      preLoaderRoute: typeof Char123LangChar125SolutionsSupportTeamsRouteImport
      parentRoute: typeof Char123LangChar125SolutionsRoute
    }
    '/{-$lang}/solutions/solo-small-teams': {
      id: '/{-$lang}/solutions/solo-small-teams'
      path: '/solo-small-teams'
      fullPath: '/{-$lang}/solutions/solo-small-teams'
      preLoaderRoute: typeof Char123LangChar125SolutionsSoloSmallTeamsRouteImport
      parentRoute: typeof Char123LangChar125SolutionsRoute
    }
    '/{-$lang}/solutions/agencies': {
      id: '/{-$lang}/solutions/agencies'
      path: '/agencies'
      fullPath: '/{-$lang}/solutions/agencies'
      preLoaderRoute: typeof Char123LangChar125SolutionsAgenciesRouteImport
      parentRoute: typeof Char123LangChar125SolutionsRoute
    }
    '/w/$slug/tickets': {
      id: '/w/$slug/tickets'
      path: '/tickets'
      fullPath: '/w/$slug/tickets'
      preLoaderRoute: typeof WSlugTicketsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/teams': {
      id: '/w/$slug/teams'
      path: '/teams'
      fullPath: '/w/$slug/teams'
      preLoaderRoute: typeof WSlugTeamsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/settings': {
      id: '/w/$slug/settings'
      path: '/settings'
      fullPath: '/w/$slug/settings'
      preLoaderRoute: typeof WSlugSettingsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/profile': {
      id: '/w/$slug/profile'
      path: '/profile'
      fullPath: '/w/$slug/profile'
      preLoaderRoute: typeof WSlugProfileRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/overview': {
      id: '/w/$slug/overview'
      path: '/overview'
      fullPath: '/w/$slug/overview'
      preLoaderRoute: typeof WSlugOverviewRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/notifications': {
      id: '/w/$slug/notifications'
      path: '/notifications'
      fullPath: '/w/$slug/notifications'
      preLoaderRoute: typeof WSlugNotificationsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/marketplace': {
      id: '/w/$slug/marketplace'
      path: '/marketplace'
      fullPath: '/w/$slug/marketplace'
      preLoaderRoute: typeof WSlugMarketplaceRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/analytics': {
      id: '/w/$slug/analytics'
      path: '/analytics'
      fullPath: '/w/$slug/analytics'
      preLoaderRoute: typeof WSlugAnalyticsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/tickets/': {
      id: '/w/$slug/tickets/'
      path: '/'
      fullPath: '/w/$slug/tickets/'
      preLoaderRoute: typeof WSlugTicketsIndexRouteImport
      parentRoute: typeof WSlugTicketsRoute
    }
    '/w/$slug/tickets/$id': {
      id: '/w/$slug/tickets/$id'
      path: '/$id'
      fullPath: '/w/$slug/tickets/$id'
      preLoaderRoute: typeof WSlugTicketsIdRouteImport
      parentRoute: typeof WSlugTicketsRoute
    }
  }
}

interface Char123LangChar125SolutionsRouteChildren {
  Char123LangChar125SolutionsAgenciesRoute: typeof Char123LangChar125SolutionsAgenciesRoute
  Char123LangChar125SolutionsSoloSmallTeamsRoute: typeof Char123LangChar125SolutionsSoloSmallTeamsRoute
  Char123LangChar125SolutionsSupportTeamsRoute: typeof Char123LangChar125SolutionsSupportTeamsRoute
}

const Char123LangChar125SolutionsRouteChildren: Char123LangChar125SolutionsRouteChildren =
  {
    Char123LangChar125SolutionsAgenciesRoute:
      Char123LangChar125SolutionsAgenciesRoute,
    Char123LangChar125SolutionsSoloSmallTeamsRoute:
      Char123LangChar125SolutionsSoloSmallTeamsRoute,
    Char123LangChar125SolutionsSupportTeamsRoute:
      Char123LangChar125SolutionsSupportTeamsRoute,
  }

const Char123LangChar125SolutionsRouteWithChildren =
  Char123LangChar125SolutionsRoute._addFileChildren(
    Char123LangChar125SolutionsRouteChildren,
  )

interface Char123LangChar125RouteRouteChildren {
  Char123LangChar125AboutRoute: typeof Char123LangChar125AboutRoute
  Char123LangChar125BlogRoute: typeof Char123LangChar125BlogRoute
  Char123LangChar125CareersRoute: typeof Char123LangChar125CareersRoute
  Char123LangChar125ChangelogRoute: typeof Char123LangChar125ChangelogRoute
  Char123LangChar125ContactRoute: typeof Char123LangChar125ContactRoute
  Char123LangChar125CustomersRoute: typeof Char123LangChar125CustomersRoute
  Char123LangChar125FeaturesRoute: typeof Char123LangChar125FeaturesRoute
  Char123LangChar125HelpRoute: typeof Char123LangChar125HelpRoute
  Char123LangChar125IntegrationsRoute: typeof Char123LangChar125IntegrationsRoute
  Char123LangChar125PricingRoute: typeof Char123LangChar125PricingRoute
  Char123LangChar125PrivacyRoute: typeof Char123LangChar125PrivacyRoute
  Char123LangChar125SecurityRoute: typeof Char123LangChar125SecurityRoute
  Char123LangChar125SolutionsRoute: typeof Char123LangChar125SolutionsRouteWithChildren
  Char123LangChar125StatusRoute: typeof Char123LangChar125StatusRoute
  Char123LangChar125TermsRoute: typeof Char123LangChar125TermsRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
}

const Char123LangChar125RouteRouteChildren: Char123LangChar125RouteRouteChildren =
  {
    Char123LangChar125AboutRoute: Char123LangChar125AboutRoute,
    Char123LangChar125BlogRoute: Char123LangChar125BlogRoute,
    Char123LangChar125CareersRoute: Char123LangChar125CareersRoute,
    Char123LangChar125ChangelogRoute: Char123LangChar125ChangelogRoute,
    Char123LangChar125ContactRoute: Char123LangChar125ContactRoute,
    Char123LangChar125CustomersRoute: Char123LangChar125CustomersRoute,
    Char123LangChar125FeaturesRoute: Char123LangChar125FeaturesRoute,
    Char123LangChar125HelpRoute: Char123LangChar125HelpRoute,
    Char123LangChar125IntegrationsRoute: Char123LangChar125IntegrationsRoute,
    Char123LangChar125PricingRoute: Char123LangChar125PricingRoute,
    Char123LangChar125PrivacyRoute: Char123LangChar125PrivacyRoute,
    Char123LangChar125SecurityRoute: Char123LangChar125SecurityRoute,
    Char123LangChar125SolutionsRoute:
      Char123LangChar125SolutionsRouteWithChildren,
    Char123LangChar125StatusRoute: Char123LangChar125StatusRoute,
    Char123LangChar125TermsRoute: Char123LangChar125TermsRoute,
    Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
  }

const Char123LangChar125RouteRouteWithChildren =
  Char123LangChar125RouteRoute._addFileChildren(
    Char123LangChar125RouteRouteChildren,
  )

interface AuthRouteChildren {
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRecoverRoute: AuthRecoverRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface WSlugTicketsRouteChildren {
  WSlugTicketsIdRoute: typeof WSlugTicketsIdRoute
  WSlugTicketsIndexRoute: typeof WSlugTicketsIndexRoute
}

const WSlugTicketsRouteChildren: WSlugTicketsRouteChildren = {
  WSlugTicketsIdRoute: WSlugTicketsIdRoute,
  WSlugTicketsIndexRoute: WSlugTicketsIndexRoute,
}

const WSlugTicketsRouteWithChildren = WSlugTicketsRoute._addFileChildren(
  WSlugTicketsRouteChildren,
)

interface WSlugRouteChildren {
  WSlugAnalyticsRoute: typeof WSlugAnalyticsRoute
  WSlugMarketplaceRoute: typeof WSlugMarketplaceRoute
  WSlugNotificationsRoute: typeof WSlugNotificationsRoute
  WSlugOverviewRoute: typeof WSlugOverviewRoute
  WSlugProfileRoute: typeof WSlugProfileRoute
  WSlugSettingsRoute: typeof WSlugSettingsRoute
  WSlugTeamsRoute: typeof WSlugTeamsRoute
  WSlugTicketsRoute: typeof WSlugTicketsRouteWithChildren
}

const WSlugRouteChildren: WSlugRouteChildren = {
  WSlugAnalyticsRoute: WSlugAnalyticsRoute,
  WSlugMarketplaceRoute: WSlugMarketplaceRoute,
  WSlugNotificationsRoute: WSlugNotificationsRoute,
  WSlugOverviewRoute: WSlugOverviewRoute,
  WSlugProfileRoute: WSlugProfileRoute,
  WSlugSettingsRoute: WSlugSettingsRoute,
  WSlugTeamsRoute: WSlugTeamsRoute,
  WSlugTicketsRoute: WSlugTicketsRouteWithChildren,
}

const WSlugRouteWithChildren = WSlugRoute._addFileChildren(WSlugRouteChildren)

interface WRouteChildren {
  WSlugRoute: typeof WSlugRouteWithChildren
}

const WRouteChildren: WRouteChildren = {
  WSlugRoute: WSlugRouteWithChildren,
}

const WRouteWithChildren = WRoute._addFileChildren(WRouteChildren)

interface WorkspacesRouteChildren {
  WorkspacesNewRoute: typeof WorkspacesNewRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesNewRoute: WorkspacesNewRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  Char123LangChar125RouteRoute: Char123LangChar125RouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  WRoute: WRouteWithChildren,
  WorkspacesRoute: WorkspacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
