/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as WRouteImport } from './routes/w'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as WSlugRouteImport } from './routes/w/$slug'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as WSlugTicketsRouteImport } from './routes/w/$slug/tickets'
import { Route as WSlugTeamsRouteImport } from './routes/w/$slug/teams'
import { Route as WSlugSettingsRouteImport } from './routes/w/$slug/settings'
import { Route as WSlugProfileRouteImport } from './routes/w/$slug/profile'
import { Route as WSlugOverviewRouteImport } from './routes/w/$slug/overview'
import { Route as WSlugNotificationsRouteImport } from './routes/w/$slug/notifications'
import { Route as WSlugMarketplaceRouteImport } from './routes/w/$slug/marketplace'
import { Route as WSlugAnalyticsRouteImport } from './routes/w/$slug/analytics'
import { Route as WSlugTicketsIndexRouteImport } from './routes/w/$slug/tickets/index'
import { Route as WSlugTicketsIdRouteImport } from './routes/w/$slug/tickets/$id'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const WRoute = WRouteImport.update({
  id: '/w',
  path: '/w',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRoute,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WRoute,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugTicketsRoute = WSlugTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugTeamsRoute = WSlugTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugSettingsRoute = WSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugProfileRoute = WSlugProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugOverviewRoute = WSlugOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugNotificationsRoute = WSlugNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugMarketplaceRoute = WSlugMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugAnalyticsRoute = WSlugAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugTicketsIndexRoute = WSlugTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugTicketsRoute,
} as any)
const WSlugTicketsIdRoute = WSlugTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WSlugTicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/w': typeof WRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/workspaces/': typeof WorkspacesIndexRoute
  '/w/$slug/analytics': typeof WSlugAnalyticsRoute
  '/w/$slug/marketplace': typeof WSlugMarketplaceRoute
  '/w/$slug/notifications': typeof WSlugNotificationsRoute
  '/w/$slug/overview': typeof WSlugOverviewRoute
  '/w/$slug/profile': typeof WSlugProfileRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/teams': typeof WSlugTeamsRoute
  '/w/$slug/tickets': typeof WSlugTicketsRouteWithChildren
  '/w/$slug/tickets/$id': typeof WSlugTicketsIdRoute
  '/w/$slug/tickets/': typeof WSlugTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/w': typeof WRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/workspaces': typeof WorkspacesIndexRoute
  '/w/$slug/analytics': typeof WSlugAnalyticsRoute
  '/w/$slug/marketplace': typeof WSlugMarketplaceRoute
  '/w/$slug/notifications': typeof WSlugNotificationsRoute
  '/w/$slug/overview': typeof WSlugOverviewRoute
  '/w/$slug/profile': typeof WSlugProfileRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/teams': typeof WSlugTeamsRoute
  '/w/$slug/tickets/$id': typeof WSlugTicketsIdRoute
  '/w/$slug/tickets': typeof WSlugTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/w': typeof WRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/workspaces/': typeof WorkspacesIndexRoute
  '/w/$slug/analytics': typeof WSlugAnalyticsRoute
  '/w/$slug/marketplace': typeof WSlugMarketplaceRoute
  '/w/$slug/notifications': typeof WSlugNotificationsRoute
  '/w/$slug/overview': typeof WSlugOverviewRoute
  '/w/$slug/profile': typeof WSlugProfileRoute
  '/w/$slug/settings': typeof WSlugSettingsRoute
  '/w/$slug/teams': typeof WSlugTeamsRoute
  '/w/$slug/tickets': typeof WSlugTicketsRouteWithChildren
  '/w/$slug/tickets/$id': typeof WSlugTicketsIdRoute
  '/w/$slug/tickets/': typeof WSlugTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/w'
    | '/workspaces'
    | '/auth/error'
    | '/w/$slug'
    | '/workspaces/'
    | '/w/$slug/analytics'
    | '/w/$slug/marketplace'
    | '/w/$slug/notifications'
    | '/w/$slug/overview'
    | '/w/$slug/profile'
    | '/w/$slug/settings'
    | '/w/$slug/teams'
    | '/w/$slug/tickets'
    | '/w/$slug/tickets/$id'
    | '/w/$slug/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/w'
    | '/auth/error'
    | '/w/$slug'
    | '/workspaces'
    | '/w/$slug/analytics'
    | '/w/$slug/marketplace'
    | '/w/$slug/notifications'
    | '/w/$slug/overview'
    | '/w/$slug/profile'
    | '/w/$slug/settings'
    | '/w/$slug/teams'
    | '/w/$slug/tickets/$id'
    | '/w/$slug/tickets'
  id:
    | '__root__'
    | '/'
    | '/w'
    | '/workspaces'
    | '/auth/error'
    | '/w/$slug'
    | '/workspaces/'
    | '/w/$slug/analytics'
    | '/w/$slug/marketplace'
    | '/w/$slug/notifications'
    | '/w/$slug/overview'
    | '/w/$slug/profile'
    | '/w/$slug/settings'
    | '/w/$slug/teams'
    | '/w/$slug/tickets'
    | '/w/$slug/tickets/$id'
    | '/w/$slug/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WRoute: typeof WRouteWithChildren
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w': {
      id: '/w'
      path: '/w'
      fullPath: '/w'
      preLoaderRoute: typeof WRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof WRoute
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/tickets': {
      id: '/w/$slug/tickets'
      path: '/tickets'
      fullPath: '/w/$slug/tickets'
      preLoaderRoute: typeof WSlugTicketsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/teams': {
      id: '/w/$slug/teams'
      path: '/teams'
      fullPath: '/w/$slug/teams'
      preLoaderRoute: typeof WSlugTeamsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/settings': {
      id: '/w/$slug/settings'
      path: '/settings'
      fullPath: '/w/$slug/settings'
      preLoaderRoute: typeof WSlugSettingsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/profile': {
      id: '/w/$slug/profile'
      path: '/profile'
      fullPath: '/w/$slug/profile'
      preLoaderRoute: typeof WSlugProfileRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/overview': {
      id: '/w/$slug/overview'
      path: '/overview'
      fullPath: '/w/$slug/overview'
      preLoaderRoute: typeof WSlugOverviewRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/notifications': {
      id: '/w/$slug/notifications'
      path: '/notifications'
      fullPath: '/w/$slug/notifications'
      preLoaderRoute: typeof WSlugNotificationsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/marketplace': {
      id: '/w/$slug/marketplace'
      path: '/marketplace'
      fullPath: '/w/$slug/marketplace'
      preLoaderRoute: typeof WSlugMarketplaceRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/analytics': {
      id: '/w/$slug/analytics'
      path: '/analytics'
      fullPath: '/w/$slug/analytics'
      preLoaderRoute: typeof WSlugAnalyticsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/tickets/': {
      id: '/w/$slug/tickets/'
      path: '/'
      fullPath: '/w/$slug/tickets/'
      preLoaderRoute: typeof WSlugTicketsIndexRouteImport
      parentRoute: typeof WSlugTicketsRoute
    }
    '/w/$slug/tickets/$id': {
      id: '/w/$slug/tickets/$id'
      path: '/$id'
      fullPath: '/w/$slug/tickets/$id'
      preLoaderRoute: typeof WSlugTicketsIdRouteImport
      parentRoute: typeof WSlugTicketsRoute
    }
  }
}

interface WSlugTicketsRouteChildren {
  WSlugTicketsIdRoute: typeof WSlugTicketsIdRoute
  WSlugTicketsIndexRoute: typeof WSlugTicketsIndexRoute
}

const WSlugTicketsRouteChildren: WSlugTicketsRouteChildren = {
  WSlugTicketsIdRoute: WSlugTicketsIdRoute,
  WSlugTicketsIndexRoute: WSlugTicketsIndexRoute,
}

const WSlugTicketsRouteWithChildren = WSlugTicketsRoute._addFileChildren(
  WSlugTicketsRouteChildren,
)

interface WSlugRouteChildren {
  WSlugAnalyticsRoute: typeof WSlugAnalyticsRoute
  WSlugMarketplaceRoute: typeof WSlugMarketplaceRoute
  WSlugNotificationsRoute: typeof WSlugNotificationsRoute
  WSlugOverviewRoute: typeof WSlugOverviewRoute
  WSlugProfileRoute: typeof WSlugProfileRoute
  WSlugSettingsRoute: typeof WSlugSettingsRoute
  WSlugTeamsRoute: typeof WSlugTeamsRoute
  WSlugTicketsRoute: typeof WSlugTicketsRouteWithChildren
}

const WSlugRouteChildren: WSlugRouteChildren = {
  WSlugAnalyticsRoute: WSlugAnalyticsRoute,
  WSlugMarketplaceRoute: WSlugMarketplaceRoute,
  WSlugNotificationsRoute: WSlugNotificationsRoute,
  WSlugOverviewRoute: WSlugOverviewRoute,
  WSlugProfileRoute: WSlugProfileRoute,
  WSlugSettingsRoute: WSlugSettingsRoute,
  WSlugTeamsRoute: WSlugTeamsRoute,
  WSlugTicketsRoute: WSlugTicketsRouteWithChildren,
}

const WSlugRouteWithChildren = WSlugRoute._addFileChildren(WSlugRouteChildren)

interface WRouteChildren {
  WSlugRoute: typeof WSlugRouteWithChildren
}

const WRouteChildren: WRouteChildren = {
  WSlugRoute: WSlugRouteWithChildren,
}

const WRouteWithChildren = WRoute._addFileChildren(WRouteChildren)

interface WorkspacesRouteChildren {
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WRoute: WRouteWithChildren,
  WorkspacesRoute: WorkspacesRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
