export interface Env {
	DB: D1Database;
	STORAGE: R2Bucket;
	AI: Ai;
	VECTORIZE_TICKETS: VectorizeIndex;
	VECTORIZE_MESSAGES: VectorizeIndex;
	VECTORIZE_CONTACTS: VectorizeIndex;
	VECTORIZE_COMPANIES: VectorizeIndex;
	VECTORIZE_MEMORIES: VectorizeIndex;
	JWT_SECRET: string;
	MS_CLIENT_ID: string;
	MS_CLIENT_SECRET: string;
	APP_URL: string;
	// Stripe
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	STRIPE_PROFESSIONAL_MONTHLY_PRICE_ID: string;
	STRIPE_PROFESSIONAL_ANNUAL_PRICE_ID: string;
	STRIPE_BUSINESS_MONTHLY_PRICE_ID: string;
	STRIPE_BUSINESS_ANNUAL_PRICE_ID: string;
}
