export interface Env {
	DB: D1Database;
	STORAGE: R2Bucket;
	AI: Ai;
	VECTORIZE_TICKETS: VectorizeIndex;
	VECTORIZE_MESSAGES: VectorizeIndex;
	VECTORIZE_CONTACTS: VectorizeIndex;
	VECTORIZE_COMPANIES: VectorizeIndex;
	VECTORIZE_MEMORIES: VectorizeIndex;
	JWT_SECRET: string;
	MS_CLIENT_ID: string;
	MS_CLIENT_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	GOOGLE_PUBSUB_TOPIC: string;
	GOOGLE_PUBSUB_SECRET: string;
	APP_URL: string;
	// Stripe
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	STRIPE_STARTER_MONTHLY_PRICE_ID: string;
	STRIPE_STARTER_ANNUAL_PRICE_ID: string;
	STRIPE_CORE_MONTHLY_PRICE_ID: string;
	STRIPE_CORE_ANNUAL_PRICE_ID: string;
	STRIPE_ENTERPRISE_MONTHLY_PRICE_ID: string;
	STRIPE_ENTERPRISE_ANNUAL_PRICE_ID: string;
}
